"""Python reference twin of the ERPsim supply chain (AA-F12), per docs/model_spec.md.

One step = one game day (DR-1). Order of events within a day (spec section 1):
  1. supplier receipts         (POs due today; L3, L4)
  2. production                (shared FIFO line, 24,000 units/day, components per recipe; B11-B13, M6)
  3. plant -> DC push          (fitted push rule; spec section 4, item 3)
  4. customer orders and sales (sale = min(order, DC stock), excess lost; B2-B4)
  5. decisions                 (forecast updates -> MRP for production and purchasing; policy rules R1-R6)

Disruptions (Phase E, docs/disruptions.md) are injected through `scenario`, a dict with optional keys:
  line_down      : [[start, end], ...]                   production line unavailable (days inclusive)
  supplier_delay : {"window": [s, e], "relative": r, "materials": [...] | None}
                   POs created in the window arrive ceil(r x sampled lead) days later
  quality        : {"window": [s, e], "block_share": b, "extra_delay": d, "materials": [...] | None}
                   receipts due in the window lose share b (blocked) and the rest arrives d days late
  demand         : {"window": [s, e], "factor": f}       customer order quantities multiplied by f
  transit        : {"window": [s, e], "days": k}         plant -> DC shipments leaving in the window arrive k days later

The twin knows nothing about SAP: everything comes from an input file built by
data/build_twin_inputs.py. Quantities are real units (the UPPAAL model divides by 100).

Modes
  forecast_mode "replay" : forecast updates replayed from the recorded year (validation, Phase D)
  demand_mode   "replay" : the recorded customer orders (day, customer, quantity) are replayed; sales are
                           still clipped to the twin's own DC stock. Isolates the supply-side physics.
                "sample" : customers order at sampled intervals and sizes (D1-D3, D5; experiments)
                "replay_all" : like "replay", plus the fraud-labelled orders (they physically took goods);
                               diagnostic use only
  line_rule     "fifo_block" : the order at the head of the line waits for its components
                "fifo_skip"  : an order short of components is skipped; the next one proceeds
                "erpsim"     : FIFO; an order starts only when components for its whole batch are in stock
                               (78 of 78 recorded starts), and switching to another product costs one
                               idle day (recorded gap between orders: median 1 day on a product switch,
                               0 days otherwise)
  mrp_timing    "recorded" : MRP (purchasing + order conversion) runs on the recorded days on which the players
                             created POs / production orders; forecast updates only change the open forecast.
                             Recorded conversion follows the forecast update by 2-5 days (player behaviour).
                "update"   : MRP runs on the forecast-update day (superseded)
  policy        "mrp"    : decisions (production orders, POs) generated by the MRP replica (experiments)
                "replay" : the players' recorded decisions are replayed: production orders (all products) on their
                           conversion days with recorded quantities and recipes, POs on their creation days with
                           recorded quantities. Validates the physics (DR-3); lead times remain sampled.
                "controller" : an external controller object makes the three real decisions each day
                           (model/twin/controllers.py): production-order conversions, POs, transfers to DCs
  push_rule     "lag1"     : output is held one day at the plant and then shipped in full (recorded: transfers
                             correlate 0.72 with the previous day's output, 0.12 with the same day's)
                "fraction" : a fixed daily fraction of plant stock is shipped (fitted; superseded)
                "replay"   : the recorded transfers per DC are replayed, clipped to the available plant stock
                "replay_deferred" : as "replay", but the clipped part of a transfer stays owed to its DC and is
                             shipped as soon as plant stock allows (validation Amendment 3: plain replay strands
                             stock at the plant whenever the twin's output is later than the recorded one)
  dc_split      "cover" : each shipment is allocated to equalise the DCs' days of cover (stock / recent daily
                          sales); recorded: the largest share went to the lowest-cover DC on 65 % of transfer
                          days (random: 33 %)
                "fixed" : fixed fitted shares (superseded)
  others        "mrp"    : the other products (F16, F15) are planned by the same MRP from their own replayed
                           forecasts and replayed sales (planning level: total stock, no customers or DCs)
                "replay" : their recorded production orders are replayed as background line load
"""
import math
from collections import defaultdict

import numpy as np
import pandas as pd

DCS = ["North", "South", "West"]


class Twin:
    def __init__(self, inp, seed=0, forecast_mode="replay", demand_mode="sample", line_rule="erpsim", others="mrp", push_rule="lag1", mrp_timing="recorded", dc_split="fixed", policy="mrp", changeover_days=0.6, scenario=None, controller=None, lead_mode="sample", lead_stream="global", observer=None,
                 reseed_from=None, demand_from=None):
        if forecast_mode != "replay":
            raise NotImplementedError("only the replay forecast mode is implemented and validated so far")
        self.demand_mode, self.line_rule, self.others, self.push_rule = demand_mode, line_rule, others, push_rule
        self.mrp_timing, self.dc_split, self.policy = mrp_timing, dc_split, policy
        self._changeover_days = changeover_days
        self.scenario = scenario or {}
        self.lead_mode = lead_mode   # "sample" or "median" (deterministic, for the UPPAAL cross-check)
        # "global": one random stream for all lead times (validation runs). "keyed": each PO's lead time is drawn
        # from a stream keyed by (seed, material, creation day, index of the PO for that material and day), so
        # runs that differ only by extra POs keep identical lead times for every other PO (common random numbers
        # for comparing decisions, AI layer L2)
        self.lead_stream, self.seed = lead_stream, seed
        self.observer = observer     # called as observer(twin, day) at the start of every day (AI layer L1 features)
        # (day, seed2): with keyed lead streams, POs created from `day` on draw from seed2 instead of seed, so the
        # history before `day` is identical to the run with `seed` (twin rollouts from an observed state)
        self.reseed_from = reseed_from
        # demand_from=(day, seed): from `day` on, every day's recorded orders (F12 and other products) are replaced by
        # those of a day drawn uniformly from the 20 days before `day`; used by planner rollouts, which must not see
        # the recorded future demand
        self.demand_from = demand_from
        self.controller = controller
        if policy == "controller" and controller is None:
            raise ValueError("policy='controller' needs a controller object")
        self.rec_orders = defaultdict(list)
        for o in inp["recorded_production_orders"] + inp["other_production_orders"]:
            self.rec_orders[o["day"]].append(o)
        self.rec_transfers = defaultdict(list)
        for t in inp.get("recorded_transfers", []):
            self.rec_transfers[t["day"]].append(t)
        self.rec_pos = defaultdict(list)
        for p_ in inp.get("recorded_pos", []):
            self.rec_pos[p_["day"]].append(p_)
        self.recent_sales = {d: [] for d in DCS}
        self.mrp_days = set(inp.get("mrp_run_days", []))
        self.planning_products = [p for p in inp.get("planning_products", [inp["product"]])
                                  if p == inp["product"] or others == "mrp"]
        self.recorded_by_product = defaultdict(list)
        for o in inp["recorded_production_orders"] + inp["other_production_orders"]:
            self.recorded_by_product[o["product"]].append(o)
        for p in self.recorded_by_product:
            self.recorded_by_product[p].sort(key=lambda o: o["day"])
        self.other_sales = {p: {int(d): q for d, q in v.items()} for p, v in inp.get("other_product_daily_sales", {}).items()}
        self.replay_orders = defaultdict(list)
        extra = inp["demand"].get("recorded_fraud_orders", []) if demand_mode == "replay_all" else []
        for o in inp["demand"].get("recorded_orders", []) + extra:
            self.replay_orders[o["day"]].append(o)
        self.inp = inp
        self.rng = np.random.default_rng(seed)
        self.product = inp["product"]
        self.components = inp["components"]
        self.cap = inp["capacity_per_day"]
        d = inp["demand"]
        self.gap_values = np.array(list(map(int, d["inter_order_days"].keys())))
        self.gap_probs = np.array(list(d["inter_order_days"].values()), dtype=float)
        self.gap_probs /= self.gap_probs.sum()
        self.qty_samples = np.array(d["order_qty_samples"])
        self.lead = {g: (np.array(list(map(int, p.keys()))), np.array(list(p.values()), dtype=float) / sum(p.values()))
                     for g, p in inp["lead_time_pmf"].items()}
        self.push = inp["dc_push"]
        self.updates = defaultdict(list)
        for u in inp["forecast_updates"]:
            self.updates[u["day"]].append(u)
        self.other_orders = defaultdict(list)
        for o in inp["other_production_orders"]:
            self.other_orders[o["day"]].append(o)
        self.recorded_f12 = sorted(inp["recorded_production_orders"], key=lambda o: o["day"])
        self._reset()

    # ------------------------------------------------------------------ state
    def _reset(self):
        self.comp = {c: 0.0 for c in self.components}          # available component stock (B16: starts empty)
        self.open_pos = []                                      # dicts: material, qty, due
        self.queue = []                                         # production orders, FIFO
        self.plant = 0.0
        self.dc = {d: 0.0 for d in DCS}
        self.open_forecast = defaultdict(float)                 # R1, per planning product
        self.other_stock = defaultdict(float)                   # other products: total finished stock
        self.direct_forecast = {"AA-P01": 0.0, "AA-P02": 0.0}  # R4c
        self.next_order = {c["id"]: c["first_order_day"] for c in self.inp["customers"]}
        self.dc_of = {c["id"]: c["dc"] for c in self.inp["customers"]}
        self.log = []
        self.in_transit = []
        self.blocked = defaultdict(float)
        self.order_log = []
        self.today = None
        self.last_product = None
        self.changeover_left = 0
        self.changeover_days = self._changeover_days
        self._po_count = {}
        self.owed = {d: 0.0 for d in DCS}                       # push_rule "replay_deferred"

    # ------------------------------------------------------------------ disruptions
    @staticmethod
    def _in(window, day):
        return window is not None and window[0] <= day <= window[1]

    def _applies(self, key, day, material=None):
        e = self.scenario.get(key)
        if not e or not self._in(e.get("window"), day):
            return None
        mats = e.get("materials")
        if material is not None and mats and material not in mats:
            return None
        return e

    def _new_po(self, material, qty, day, lead=None, quality_exempt=False):
        lead = self._lead(material, day) if lead is None else lead
        e = self._applies("supplier_delay", day, material)
        if e:
            lead += math.ceil(e["relative"] * lead)
        po = {"material": material, "qty": qty, "due": day + lead}
        if quality_exempt:
            po["quality_done"] = True     # a replacement delivery is not blocked again (observed events are single)
        self.open_pos.append(po)

    # ------------------------------------------------------------------ helpers
    def _gap(self):
        return int(self.rng.choice(self.gap_values, p=self.gap_probs))

    def _qty(self):
        return float(self.rng.choice(self.qty_samples))

    def _lead(self, material, day=None):
        vals, p = self.lead["food" if material.startswith("AA-R") else "packaging"]
        if self.lead_mode == "median":
            return int(vals[np.searchsorted(np.cumsum(p), 0.5)])
        if self.lead_stream == "keyed" and day is not None:
            key = (material, day)
            k = self._po_count[key] = self._po_count.get(key, -1) + 1
            sd = self.seed
            if self.reseed_from is not None and day >= self.reseed_from[0]:
                sd = self.reseed_from[1]
            g = np.random.default_rng([sd, self.components.index(material), day, k])
            return int(g.choice(vals, p=p))
        return int(self.rng.choice(vals, p=p))

    def _lots(self, q, product):
        r = self.inp["lot_rules"][product]
        if q <= 0:
            return []
        q = math.ceil(q / r["rounding"]) * r["rounding"]
        out = []
        while q > r["max"]:
            out.append(r["max"])
            q -= r["max"]
        out.append(max(q, r["min"]))
        return out

    def _recipe_in_force(self, day, product=None):
        """R4b: the recipe of the next recorded order of `product` created on/after `day`, else the last one."""
        orders = self.recorded_by_product[product or self.product]
        for o in orders:
            if o["day"] >= day:
                return o["recipe"]
        return orders[-1]["recipe"]

    # ------------------------------------------------------------------ day steps
    def _receipts(self, day):
        due = [p for p in self.open_pos if p["due"] <= day]
        self.open_pos = [p for p in self.open_pos if p["due"] > day]
        got = 0.0
        for p in due:
            e = None if p.get("quality_done") else self._applies("quality", day, p["material"])
            if e:
                blocked = p["qty"] * e["block_share"]
                self.blocked[p["material"]] += blocked
                if self.policy in ("replay", "controller") and blocked > 0:
                    # minimal reaction of the accepted MRP replica (rule R5): blocked stock is not available, so
                    # the net requirement rises by the blocked quantity and a replacement PO is placed today
                    self._new_po(p["material"], blocked, day, quality_exempt=True)
                rest = p["qty"] - blocked
                if e.get("extra_delay", 0) > 0:
                    self.open_pos.append({"material": p["material"], "qty": rest, "due": day + e["extra_delay"],
                                          "quality_done": True})
                    continue
                p = dict(p, qty=rest)
            self.comp[p["material"]] += p["qty"]
            got += p["qty"]
        return got

    def _can_start(self, o):
        return all(self.comp[c] + 1e-6 >= r * o["remaining"] for c, r in o["recipe"].items() if r > 0)

    def _produce(self):
        cap, out_f12, out_other = self.cap, 0.0, 0.0
        if any(self._in(w, self.today) for w in self.scenario.get("line_down", [])):
            return out_f12, out_other
        if self.line_rule == "erpsim":
            # changeover = capacity lost when the line switches product (in units, may span days)
            used = min(self.changeover_left, cap)
            self.changeover_left -= used
            cap -= used
            while self.queue and cap > 0:
                o = self.queue[0]
                if "start" not in o:
                    if not self._can_start(o):
                        break                                   # waits for its full batch
                    if self.last_product is not None and o["product"] != self.last_product:
                        self.last_product = o["product"]
                        self.changeover_left = self.changeover_days * self.cap
                        used = min(self.changeover_left, cap)
                        self.changeover_left -= used
                        cap -= used
                        if cap <= 0:
                            break
                    o["start"] = self.today
                    self.order_log.append({"product": o["product"], "created": o["day"], "start": self.today})
                q = min(o["remaining"], cap)
                for c, r in o["recipe"].items():
                    self.comp[c] -= r * q
                o["remaining"] -= q
                cap -= q
                self.last_product = o["product"]
                if o["product"] == self.product:
                    self.plant += q
                    out_f12 += q
                else:
                    self.other_stock[o["product"]] += q
                    out_other += q
                if o["remaining"] <= 0:
                    self.queue.pop(0)
            return out_f12, out_other
        i = 0
        while i < len(self.queue) and cap > 0:
            o = self.queue[i]
            limit = min(o["remaining"], cap)
            for c, r in o["recipe"].items():
                if r > 0:
                    limit = min(limit, math.floor(self.comp[c] / r))
            if limit <= 0:
                if self.line_rule == "fifo_block":
                    break          # the order at the head waits for its components
                i += 1             # fifo_skip: try the next order
                continue
            for c, r in o["recipe"].items():
                self.comp[c] -= r * limit
            if "start" not in o:
                o["start"] = self.today
                self.order_log.append({"product": o["product"], "created": o["day"], "start": self.today})
            o["remaining"] -= limit
            cap -= limit
            if o["product"] == self.product:
                self.plant += limit
                out_f12 += limit
            else:
                self.other_stock[o["product"]] += limit
                out_other += limit
            if o["remaining"] <= 0:
                self.queue.pop(i)
            else:
                i += 1
        return out_f12, out_other

    def _to_dc(self, d, q):
        e = self._applies("transit", self.today)
        if e:
            self.in_transit.append({"dc": d, "qty": q, "due": self.today + e["days"]})
        else:
            self.dc[d] += q

    def _arrivals(self):
        arrived = [t for t in self.in_transit if t["due"] <= self.today]
        self.in_transit = [t for t in self.in_transit if t["due"] > self.today]
        for t in arrived:
            self.dc[t["dc"]] += t["qty"]

    def _push(self, carried):
        if self.policy == "controller":
            plan = self.controller.transfers(self, self.today, carried) or {}
            sent, done = 0.0, {}
            for d in DCS:
                q = max(0.0, min(plan.get(d, 0.0), self.plant - sent))
                if q > 0:
                    self._to_dc(d, q)
                    sent += q
                    done[d] = q
            self.plant -= sent
            if hasattr(self.controller, "shipped"):
                self.controller.shipped(done)
            return sent
        if self.push_rule == "replay":
            sent = 0.0
            for t in self.rec_transfers.get(self.today, []):
                q = min(t["qty"], self.plant - sent)
                if q > 0:
                    self._to_dc(t["dc"], q)
                    sent += q
            self.plant -= sent
            return sent
        if self.push_rule == "replay_deferred":
            sent = 0.0
            for t in self.rec_transfers.get(self.today, []):
                self.owed[t["dc"]] += t["qty"]
            for d in DCS:
                q = min(self.owed[d], self.plant - sent)
                if q > 0:
                    self._to_dc(d, q)
                    self.owed[d] -= q
                    sent += q
            self.plant -= sent
            return sent
        if self.push_rule == "lag1":
            ship = carried                     # everything that was already at the plant before today's output
        else:
            ship = math.floor(self.plant * self.push["daily_fraction_of_plant_stock"])
        sent = 0.0
        if self.dc_split == "cover" and ship > 0:
            rate = {d: max(np.mean(self.recent_sales[d][-20:]) if self.recent_sales[d] else 1.0, 1.0) for d in DCS}
            # water-filling: raise the lowest days-of-cover level until the shipment is used up
            lo, hi = 0.0, (sum(self.dc.values()) + ship) / min(rate.values()) + 1
            for _ in range(60):
                mid = (lo + hi) / 2
                need = sum(max(0.0, mid * rate[d] - self.dc[d]) for d in DCS)
                lo, hi = (mid, hi) if need < ship else (lo, mid)
            alloc = {d: max(0.0, lo * rate[d] - self.dc[d]) for d in DCS}
            tot = sum(alloc.values()) or 1.0
            for i, d in enumerate(DCS):
                q = (ship - sent) if i == len(DCS) - 1 else math.floor(ship * alloc[d] / tot)
                self._to_dc(d, q)
                sent += q
        else:
            for i, d in enumerate(DCS):
                q = (ship - sent) if i == len(DCS) - 1 else math.floor(ship * self.push["dc_shares"].get(d, 0))
                self._to_dc(d, q)
                sent += q
        self.plant -= sent
        return sent

    def _source_day(self, day):
        if self.demand_from is None or day < self.demand_from[0]:
            return day
        s0 = self.demand_from[0]
        g = np.random.default_rng([self.demand_from[1], day])
        return int(g.integers(max(1, s0 - 20), s0))

    def _demand_factor(self, day):
        e = self._applies("demand", day)
        return e["factor"] if e else 1.0

    def _sales(self, day):
        sold, lost = defaultdict(float), defaultdict(float)
        if self.demand_mode in ("replay", "replay_all"):
            for o in self.replay_orders.get(self._source_day(day), []):
                dc = self.dc_of.get(o["customer"])
                if dc is None:
                    continue
                qty = o["qty"] * self._demand_factor(day)
                s = min(qty, self.dc[dc])
                self.dc[dc] -= s
                sold[dc] += s
                lost[dc] += qty - s
            return sold, lost
        for k, nd in self.next_order.items():
            if nd != day:
                continue
            dc = self.dc_of[k]
            q = self._qty() * self._demand_factor(day)
            s = min(q, self.dc[dc])
            self.dc[dc] -= s
            sold[dc] += s
            lost[dc] += q - s
            self.next_order[k] = day + self._gap()
        return sold, lost

    def _other_sales(self, day):
        """Other products at planning level: replayed sales, clipped to their total stock. Returns the lost units."""
        lost = 0.0
        for p in self.planning_products:
            if p == self.product:
                continue
            q = self.other_sales.get(p, {}).get(self._source_day(day), 0.0)
            s = min(q, self.other_stock[p])
            self.other_stock[p] -= s
            lost += q - s
            self.open_forecast[p] = max(0.0, self.open_forecast[p] - s)
        return lost

    def _decide_replay(self, day):
        # physics uses what was actually issued (differs from the reservation for partly issued orders)
        created = [{"product": o["product"], "qty": o["qty"], "remaining": o["qty"],
                    "recipe": o.get("issued_recipe") or o["recipe"], "day": day}
                   for o in self.rec_orders.get(day, [])]
        self.queue.extend(created)
        for p_ in self.rec_pos.get(day, []):
            if p_.get("pre_start"):                                                       # initial stock at start
                self.open_pos.append({"material": p_["material"], "qty": p_["qty"], "due": day + 1})
            else:
                self._new_po(p_["material"], p_["qty"], day)
        return bool(created or self.rec_pos.get(day)), len(created)

    def _decide(self, day):
        if self.policy == "replay":
            return self._decide_replay(day)
        if self.policy == "controller":
            created = [{"product": p, "qty": q, "remaining": q, "recipe": r, "day": day}
                       for p, q, r in self.controller.production_orders(self, day)]
            self.queue.extend(created)
            pos = self.controller.purchase_orders(self, day)
            for m, q in pos:
                self._new_po(m, q, day)
            return bool(created or pos), len(created)
        run_for = []
        for u in self.updates.get(day, []):
            if u["material"] in self.planning_products:
                self.open_forecast[u["material"]] = u["open_qty"]   # R1: new open forecast
                run_for.append(u["material"])
            elif u["material"] in self.direct_forecast:
                self.direct_forecast[u["material"]] = u["open_qty"]
        if self.mrp_timing == "recorded":
            run_for = list(self.planning_products) if day in self.mrp_days else []
        created = []
        for p in dict.fromkeys(run_for):                            # R2, R3 (one run per product per day)
            open_prod = sum(o["remaining"] for o in self.queue if o["product"] == p)
            stock = self.plant + sum(self.dc.values()) if p == self.product else self.other_stock[p]
            net = self.open_forecast[p] - stock - open_prod
            recipe = self._recipe_in_force(day, p)
            for q in self._lots(net, p):
                created.append({"product": p, "qty": q, "remaining": q, "recipe": recipe, "day": day})
        if self.others == "replay":                                 # background load (DR-2), replayed
            for o in self.other_orders.get(day, []):
                created.append({"product": o["product"], "qty": o["qty"], "remaining": o["qty"],
                                "recipe": o["recipe"], "day": day})
        mrp = bool(run_for)
        self.queue.extend(created)
        if mrp or created:                               # R4, R5, R6: purchasing
            gross = defaultdict(float)
            for o in self.queue:
                for c, r in o["recipe"].items():
                    gross[c] += r * o["remaining"]
            for c, q in self.direct_forecast.items():
                gross[c] += q
            for c in self.components:
                on_order = sum(p["qty"] for p in self.open_pos if p["material"] == c)
                net = gross[c] - self.comp[c] - on_order
                if net > 1e-6:
                    r = self.inp["po_rounding"][c]
                    q = math.ceil(round(net, 6) / r) * r
                    self._new_po(c, q, day)
        return mrp, len(created)

    # ------------------------------------------------------------------ run
    def run(self):
        first, last = self.inp["days"]["first"], self.inp["days"]["last"]
        for day in range(first - 1, last + 1):
            self.today = day
            if self.observer:
                self.observer(self, day)
            self._arrivals()
            received = self._receipts(day)
            carried = self.plant
            before = dict(self.comp)
            out_f12, out_other = self._produce()
            self.last_consumption = {c: before[c] - self.comp[c] for c in self.components}
            sent = self._push(carried)
            sold, lost = self._sales(day)
            for d in DCS:
                self.recent_sales[d].append(sold[d] + lost[d])
            self.open_forecast[self.product] = max(0.0, self.open_forecast[self.product] - sum(sold.values()))  # R1
            lost_other = self._other_sales(day)
            mrp, n_created = self._decide(day)
            row = {"day": day, "received": received, "production_f12": out_f12, "production_other": out_other,
                   "transferred": sent, "sales": sum(sold.values()), "lost": sum(lost.values()),
                   "plant_stock": self.plant, "queue_orders": len(self.queue),
                   "queue_f12_units": sum(o["remaining"] for o in self.queue if o["product"] == self.product),
                   "open_po_qty": sum(p["qty"] for p in self.open_pos), "mrp_run": mrp, "orders_created": n_created,
                   "lost_other": lost_other}
            for d in DCS:
                row[f"dc_{d}"] = self.dc[d]
                row[f"sales_{d}"] = sold[d]
                row[f"lost_{d}"] = lost[d]
            for c in self.components:
                row[f"stock_{c}"] = self.comp[c]
            self.log.append(row)
        return pd.DataFrame(self.log)
